name: Grant Ebeling
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
permalink: /:categories/:title
theme: jekyll-theme-minimal

baseurl: ""
url: "https://urhokarila.github.io/"

highlighter: rouge

parse_block_html: true
parse_span_html: true
index: 0